version: '2'
services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: my-root-db-pw
  rc:
    depends_on:
      - db
    image: number13/roundcube:latest
    ports:
      - "80:80"
    restart: always
    environment:
      SRV_NAME: example.com
      DB_USR: roundcube-usr
      DB_PW: dbpw
      DB_HOST: mysql
      DB_ROOT_PW: my-root-db-pw
      IMAP_SRV: imap.example.com
      SMTP_SRV: smtp.example.com
      SUPP_URL: support.example.com
      MAIL_NAME: "example.com"
      LANG: en_US
      RC_TIMEZONE: Europe/Berlin
      VMAIL_DB_USER: postfix
      VMAIL_DB_PW: my-secret-database-pw
      VMAIL_DB_HOST: myvmaildb
volumes:
  db_data:






