version: '2'
services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: test
        MYSQL_USER: root
        MYSQL_PASSWORD: test
  rc:
    depends_on:
      - db
    image: number13/roundcube:latest
    ports:
      - "80:80"
    restart: always
    environment:
      SRV_NAME: example.com
      DB_USR: root
      DB_PW: dbpw
      DB_HOST: mysql
      IMAP_SRV: imap.example.com
      SMTP_SRV: smtp.example.com
      SUPP_URL: support.example.com
      MAIL_NAME: "example.com"
      LANG: en_US
      RC_TIMEZONE: Europe/Berlin
volumes:
  db_data:






